info:
    description: "EmplyeeRest REST API"
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "EmplyeeRest"
    version: v1.0
openapi: 3.0.1
paths:
  "/get-employee-list":
    get: 
      operationId: getEmployeeList
      responses: 
        '200':
          description: List of employees.
          content: 
            application/json: 
              schema: 
                items:
                  $ref: "#/components/schemas/EmployeeDetails"
            application/xml: 
              schema:
                items:
                  $ref: "#/components/schemas/EmployeeDetails"
      tags: ["EmployeeDetails"]
  "/get-employee-by-id":
    get:
      operationId: getEmployeeById
      parameters:
        - in: query
          name: employeeId
          required: true
          schema:
            type: integer
            format: int64
      responses: 
        '200':
          description: List of employees.
          content: 
            application/json: 
              schema: 
                  $ref: "#/components/schemas/EmployeeDetails"
            application/xml: 
              schema:
                items:
                  $ref: "#/components/schemas/EmployeeDetails"
      tags: ["EmployeeDetails"]
  "/insert-employee":
    post:
      operationId: insertEmployee
      requestBody:
        content:
          application/json: 
              schema: 
                  $ref: "#/components/schemas/EmployeeDetails"
          application/xml: 
              schema:
                  $ref: "#/components/schemas/EmployeeDetails"
      responses: 
        '200':
          description: insert successful
          content: 
            application/json: 
              schema: 
                  $ref: "#/components/schemas/Status"
            application/xml: 
              schema:
                items:
                  $ref: "#/components/schemas/Status"
      tags: ["EmployeeDetails"]
  "/delete-employee":
    delete:
      operationId: deleteEmployee
      parameters:
        - in: query
          name: employeeId
          required: true
          schema:
            type: integer
            format: int64
      responses: 
        '200':
          description: deleted successfully
          content: 
            application/json: 
              schema: 
                  $ref: "#/components/schemas/Status"
            application/xml: 
              schema:
                items:
                  $ref: "#/components/schemas/Status"
      tags: ["EmployeeDetails"]
components: 
  schemas: 
    EmployeeDetails:
      description: Employee entity
      properties: 
        employeeId:
          description: employee id.
          type: integer
          format: int64
        firstName:
          description: employees first name
          type: string
        lastName:
          description: employee Last name
          type: string
        emailAddress:
          description: email address of employee
          type: string
        mobileNumber:
          description: mobile number
          type: string
    Status:
      description: Responce Status
      properties: 
        statusCode:
          description: employee id.
          type: integer
        message:
          description: employees first name
          type: string